name: Codex Log Commit
on:
  push:
    paths:
      - codex_log.md
jobs:
  codex-log:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Commit log safely
        run: |
          git config user.name "Codex Bot"
          git config user.email "codex@monster.dev"
          git pull --rebase origin main || true
          git add codex_log.md
          git commit -m "🤖 Codex log update" || echo "No changes"
          git push origin main
