name: Auto-merge Codex PRs

on:
  pull_request:
    types:
      - opened
      - labeled
      - synchronize

jobs:
  automerge:
    if: contains(github.event.pull_request.labels.*.name, 'codex')
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Enable GitHub auto-merge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
